#!/usr/bin/env python3
"""Convert the members' survey export (.xlsx) into _data/people.yml.

The Google Form export is the upstream source of truth; _data/people.yml is
what the site actually renders, sorted 가나다순. Re-run this after a new export
and read the diff before committing.

    python3 tools/import_people.py ~/Downloads/<survey export>.xlsx

Expected columns (Google Forms question order):
    A timestamp   B name(ko)    C name(en)   D affiliation(ko) E affiliation(en)
    F field(ko)   G field(en)   H email      I photo(drive)    J bio(ko)
    K bio(en)     L link        M past presentation titles

Column I is handled by tools/fetch_photos.py, which writes the separate
_data/people_photos.yml. Column M duplicates what _seminar/ already records,
so it is skipped.

Hand edits to this file are overwritten, with one exception: paragraph breaks
added to bios by tools/paragraph_bios.py are kept, since bios are compared
with whitespace removed and the form has no way to express them.
"""

import os
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
M = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

FIELDS = [
    ("name", "B"),
    ("name_en", "C"),
    ("affiliation", "D"),
    ("affiliation_en", "E"),
    ("field", "F"),
    ("field_en", "G"),
    ("email", "H"),
    ("bio", "J"),
    ("bio_en", "K"),
    ("link", "L"),
]

# Personal links show as a platform name rather than a raw URL. Anything not
# recognised falls back to its bare domain, which reads the same in KO and EN.
PLATFORMS = [
    ("linkedin.com", "LinkedIn"),
    ("notion.site", "Notion"),
    ("notion.so", "Notion"),
    ("github.com", "GitHub"),
    ("instagram.com", "Instagram"),
    ("x.com", "X"),
    ("twitter.com", "X"),
    ("orcid.org", "ORCID"),
    ("scholar.google", "Google Scholar"),
    ("academia.edu", "Academia.edu"),
    ("researchgate.net", "ResearchGate"),
    ("brunch.co.kr", "brunch"),
    ("tistory.com", "Tistory"),
    ("velog.io", "velog"),
]


def link_label(url):
    """A human label for a personal link: platform name, else the bare domain."""
    host = re.sub(r"^https?://", "", url).split("/")[0].lower()
    for needle, label in PLATFORMS:
        if needle in host:
            return label
    return re.sub(r"^www\.", "", host)

OUT_PATH = "_data/people.yml"
PENDING_PATH = "_data/people_pending.yml"  # replies that arrived after the export

HEADER = """# Members, generated by tools/import_people.py from the survey export.
# Rendered by people.html. Re-run the importer rather than editing by hand.
"""


def read_rows(path):
    """Return the sheet as a list of {column letter: value} dicts, minus the header."""
    z = zipfile.ZipFile(path)
    shared = [
        "".join(t.text or "" for t in si.iter(M + "t"))
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)
    ]

    rows = {}
    for row in ET.fromstring(z.read("xl/worksheets/sheet1.xml")).iter(M + "row"):
        cells = {}
        for c in row.findall("m:c", NS):
            v = c.find("m:v", NS)
            if v is None or v.text is None:
                continue
            value = shared[int(v.text)] if c.get("t") == "s" else v.text
            cells[re.sub(r"\d+$", "", c.get("r"))] = value
        rows[int(row.get("r"))] = cells

    return [rows[i] for i in sorted(rows) if i >= 2]


# Romanisations actually used by this group, keyed by the Korean surname.
# Used only to find which token of an English name is the surname -- never to
# respell one, so 이용우 stays "Yi" while 이나현 stays "Lee".
SURNAMES = {
    "김": ["Kim"], "이": ["Lee", "Yi", "Rhee", "Ri"], "박": ["Park", "Pak"],
    "서": ["Suh", "Seo"], "성": ["Seong", "Sung"], "안": ["Ahn", "An"],
    "엄": ["Eom", "Um"], "유": ["Yu", "Yoo", "Ryu"], "윤": ["Yun", "Yoon"],
    "전": ["Jeon", "Jun", "Chun"], "정": ["Jeong", "Jung", "Chung"],
    "조": ["Cho", "Jo"], "진": ["Jin", "Chin"], "황": ["Hwang"],
    "최": ["Choi", "Choe"], "강": ["Kang"], "장": ["Jang", "Chang"],
    "한": ["Han"], "오": ["Oh", "O"], "신": ["Shin"], "권": ["Kwon"],
    "송": ["Song"], "홍": ["Hong"], "문": ["Moon", "Mun"], "손": ["Son"],
}


def given_name_first(name_ko, name_en):
    """Reorder an English name to 'Given Surname'.

    Answers arrived both ways -- "Kim Nawon" beside "Jihyun Kim" -- and the
    mix reads as an error. The surname is identified by matching a token
    against the romanisations of the Korean surname, so nothing is respelled
    and a name whose surname cannot be identified is left exactly as typed.
    """
    tokens = name_en.split()
    if len(tokens) < 2 or not name_ko:
        return name_en

    options = [r.lower() for r in SURNAMES.get(name_ko[0], [])]
    if not options:
        return name_en

    for i, token in enumerate(tokens):
        if token.lower() in options:
            return " ".join(tokens[:i] + tokens[i + 1:] + [tokens[i]])
    return name_en


def title_case(name):
    """Normalise a romanised name to Title Case.

    People typed these however they liked -- "CHANHEE LEE", "yu mireu",
    "EOM Yoon ju" -- and the mix looks like inconsistency rather than
    intent. The trailing comma in a surname-first entry ("Ahn, Jinho") goes
    too, so every name reads as plain words.
    """
    words = name.replace(",", " ").split()
    return " ".join(w[:1].upper() + w[1:].lower() for w in words)


# Answers that need a correction the form cannot make on its own. Kept here,
# and applied on every run, so a re-import does not quietly undo them.
OVERRIDES = {
    # Put the research interests in the bio field, not the one-line 전공 slot,
    # where they render as "Seoul National University · Art History | Research
    # interests: ..." beside everyone else's plain department name.
    ("김지현", "field_en"): "Art History",
    # typed without spaces around the ampersand, unlike every other answer
    ("이나현", "field_en"): "Political Science & International Relations",
    # supplied after the survey closed
    ("이용우", "link"): "https://www.linkedin.com/in/yongwoo-yi-331653381/",
    # her own site rather than the LinkedIn profile given on the form
    ("조민경", "link"): "https://minkyung.me",
}

# The site is written in American spelling, but answers arrive in both. Listed
# word by word rather than by rule: a blanket -ise -> -ize would also hit
# "surprise", "exercise" and "precise", and -re -> -er would hit "genre".
BRITISH = {
    "behaviour": "behavior", "behavioural": "behavioral",
    "colour": "color", "coloured": "colored",
    "favour": "favor", "favourite": "favorite",
    "honour": "honor", "labour": "labor", "neighbour": "neighbor",
    "centre": "center", "centres": "centers", "theatre": "theater",
    "metre": "meter", "metres": "meters", "fibre": "fiber",
    "programme": "program", "programmes": "programs",
    "catalogue": "catalog", "dialogue": "dialog",
    "defence": "defense", "offence": "offense",
    "modelling": "modeling", "travelled": "traveled", "travelling": "traveling",
    "whilst": "while", "amongst": "among", "judgement": "judgment",
    "learnt": "learned", "spelt": "spelled", "practise": "practice",
}
# -ise verbs and their families, which are regular enough to expand
for _stem in ("analy", "organi", "reali", "recogni", "speciali", "emphasi",
              "normali", "summari", "characteri", "criticis", "prioriti",
              "utili", "apologi", "memori", "civili", "globali", "conceptuali",
              "contextuali", "maximi", "minimi", "institutionali"):
    _stem = _stem.rstrip("s")
    for _suffix, _us in (("se", "ze"), ("sed", "zed"), ("ses", "zes"),
                         ("sing", "zing"), ("sation", "zation"), ("sations", "zations")):
        BRITISH[_stem + _suffix] = _stem + _us

_BRITISH_RE = re.compile(r"\b(%s)\b" % "|".join(sorted(BRITISH, key=len, reverse=True)), re.I)


def americanize(text):
    """Convert British spellings to American, preserving capitalisation."""
    def swap(match):
        word = match.group(0)
        fixed = BRITISH[word.lower()]
        return fixed.capitalize() if word[0].isupper() else fixed
    return _BRITISH_RE.sub(swap, text)


MINOR_WORDS = {"of", "and", "the", "for", "in", "on", "at", "to"}


def sentence_case(text):
    """Fix answers typed in all caps, leaving acronyms alone.

    "SEOUL NATIONAL UNIVERSITY" is shouting; "KAIST CT" and "LMU Munich" are
    how those names are actually written. The test is whether the string has
    any lowercase at all and whether it contains a word too long to be an
    acronym -- five letters or fewer stays untouched.
    """
    if any(c.islower() for c in text):
        return text
    if not any(len(w.strip(",.&")) >= 6 for w in text.split()):
        return text

    words = []
    for i, word in enumerate(text.split()):
        lowered = word.lower()
        if i and lowered.strip(",") in MINOR_WORDS:
            words.append(lowered)
        else:
            words.append(lowered[:1].upper() + lowered[1:])
    return " ".join(words)


def department_case(text):
    """Normalise an English field-of-study answer.

    Some people wrote "Department of History" and others just "Philosophy";
    some capitalised the phrase and some did not. The prefix goes and the
    result is Title Case, so the column reads as one list rather than as
    twenty separately-worded answers. All-caps tokens are left alone so an
    acronym is not turned into a word.
    """
    text = re.sub(r"^(the\s+)?department\s+of\s+", "", text, flags=re.I).strip()
    words = []
    for i, word in enumerate(text.split()):
        bare = word.strip(",&")
        if bare.isupper() and len(bare) > 1:
            words.append(word)
        elif i and bare.lower() in MINOR_WORDS:
            words.append(word.lower())
        else:
            words.append(word[:1].upper() + word[1:])
    return " ".join(words)


def clean(value):
    """Normalise a cell: strip stray whitespace, drop zero-width junk from pasted text."""
    if not value:
        return ""
    value = value.replace("\r\n", "\n").replace("​", "").replace("\xa0", " ")
    return "\n".join(line.strip() for line in value.split("\n")).strip("\n ")


ENTRY_RE = re.compile(r"^(- |  )(\w+): (.*)$")


def read_existing(path):
    """Parse a people.yml this script wrote earlier, keyed by Korean name.

    Only handles the subset of YAML emit() produces -- quoted scalars and
    literal blocks -- which is enough, since nothing else writes this file.
    """
    if not os.path.exists(path):
        return {}

    lines = open(path, encoding="utf-8").read().split("\n")
    entries, cur, i = [], None, 0
    while i < len(lines):
        m = ENTRY_RE.match(lines[i])
        if not m:
            i += 1
            continue

        marker, key, value = m.groups()
        if marker == "- ":
            cur = {}
            entries.append(cur)
        if cur is None:
            i += 1
            continue

        if value == "|-":
            block, i = [], i + 1
            while i < len(lines):
                line = lines[i]
                if line.startswith("    "):
                    block.append(line[4:])
                elif line == "" and i + 1 < len(lines) and lines[i + 1].startswith("    "):
                    block.append("")  # blank line inside the block, not the end of it
                else:
                    break
                i += 1
            cur[key] = "\n".join(block).rstrip()
            continue

        cur[key] = value.strip('"').replace('\\"', '"').replace("\\\\", "\\")
        i += 1

    return {e["name"]: e for e in entries if e.get("name")}


def squash(text):
    """Text with all whitespace removed, for comparing wording independently
    of how it happens to be broken into lines and paragraphs."""
    return re.sub(r"\s+", "", text or "")


def emit(key, value, indent="  "):
    """Render one YAML key. Multi-line values become literal blocks."""
    if "\n" in value:
        body = "\n".join(indent + "  " + line if line else "" for line in value.split("\n"))
        return "%s%s: |-\n%s" % (indent, key, body)
    return '%s%s: "%s"' % (indent, key, value.replace("\\", "\\\\").replace('"', '\\"'))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    out = [HEADER]
    # 가나다순. Precomposed Hangul syllables sit in 가나다 order in Unicode, so a
    # plain codepoint sort is the right collation here; sorting the file itself
    # rather than the template keeps diffs stable across re-imports, since the
    # export arrives in whatever order people happened to answer the form.
    people = sorted(read_rows(sys.argv[1]), key=lambda row: clean(row.get("B")))
    existing = read_existing(OUT_PATH)
    kept = 0

    for person in people:
        entry = []
        prior = existing.get(clean(person.get("B")), {})
        for key, column in FIELDS:
            value = clean(person.get(column))
            value = OVERRIDES.get((clean(person.get("B")), key), value)
            if key == "name_en":
                value = given_name_first(clean(person.get("B")), title_case(value))
            elif key == "affiliation_en":
                value = americanize(sentence_case(value))
            elif key == "field_en":
                value = americanize(department_case(sentence_case(value)))
            elif key == "bio_en":
                value = americanize(value)
            # Long bios are broken into paragraphs by hand for readability.
            # That editing is invisible to the form, so a re-import would undo
            # it; keep the edited text whenever the wording itself is unchanged.
            if key in ("bio", "bio_en") and squash(prior.get(key)) == squash(value) != "":
                if prior[key] != value:
                    kept += 1
                value = prior[key]
            if value:
                entry.append(emit(key, value))
        # Sorting key for the English view. Names display given-name-first, but
        # a list of people is conventionally alphabetised by surname, so this
        # puts the surname in front purely for ordering. Falls back to the
        # displayed name when the surname could not be identified.
        name_en = title_case(clean(person.get("C")))
        display = given_name_first(clean(person.get("B")), name_en)
        parts = display.split()
        if len(parts) > 1:
            entry.append(emit("sort_en", " ".join([parts[-1]] + parts[:-1]).lower()))
        elif display:
            entry.append(emit("sort_en", display.lower()))

        link = OVERRIDES.get((clean(person.get("B")), "link"), clean(person.get("L")))
        if link:
            entry.append(emit("link_label", link_label(link)))
        # entries are indented two spaces; the first one carries the "- " marker
        out.append("- " + "\n".join(entry)[2:])

    # Late replies, merged in and sorted with the rest. Anyone who has since
    # answered the form is dropped here, so the export stays authoritative.
    exported = {clean(p.get("B")) for p in people}
    pending = [e for n, e in read_existing(PENDING_PATH).items() if n not in exported]
    for entry in pending:
        fields = [(k, v) for k, v in entry.items() if k != "photo_drive_id"]
        out.append("- " + "\n".join(emit(k, v) for k, v in fields)[2:])
    if pending:
        print("merged %d pending member(s): %s"
              % (len(pending), ", ".join(e["name"] for e in pending)))

    # re-sort so the merged entries land in 가나다 order rather than at the end
    header, entries = out[0], out[1:]
    entries.sort(key=lambda block: re.search(r'name: "?([^"\n]+)', block).group(1))
    out = [header] + entries

    text = "\n\n".join(out) + "\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s (%d members)" % (OUT_PATH, len(people)))
    if kept:
        print("kept hand-edited paragraphing on %d bio field(s)" % kept)


if __name__ == "__main__":
    main()
